name: Upload to release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build
    - name: Find jar file
      run: path=$(find . -path '*/build/libs/*.jar'); path_to_jar=$(basename $path .jar); export JAR_NAME=$path_to_jar
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.JAR_NAME }}
        path: ./build/libs/${{ env.JAR_NAME }}
