name: Upload to release

on:
  release:
    types: [published, edited]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Upload to release

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@master
      env:
        JAR_PATH: $(find . -path '*/build/libs/*.jar') 
      with:
        name: sonar-bsl-plugin-community
        path: ./build/libs/${{ env.JAR_NAME }}
    - name: Upload jar to release
      uses: AButler/upload-release-assets@v1.0
      env:
        JAR_PATH: $(find . -path '*/build/libs/*.jar')
      with:
        files: '${{ env.JAR_NAME }}'
        repo-token: ${{ secrets.GITHUB_TOKEN }} 
